---
apiVersion: v1
kind: Pod
metadata:
  name: nssf
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
         "name" : "privnet"
      }
    ]'
spec:
  containers:
  - image: "artifactory.haifa.ibm.com:5130/weit/free5gc-nssf"
    command: ["./nssf", "-nssfcfg", "../config/nssfcfg.yaml"]
    imagePullPolicy: Always
    name: nssf
    env:
    - name: GIN_MODE
      value: "release"
    volumeMounts:
      - name: nssf-volume
        mountPath: /free5gc/config/

  restartPolicy: Always
  volumes:
    - name: nssf-volume
      configMap:
        defaultMode: 420
        name: nssf-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-conf
  labels:
    name: nssf-conf
data:
  nssfcfg.yaml: |-
    info:
      version: 1.0.0
      description: NSSF initial local configuration
    
    configuration:
      nssfName: NSSF # the name of this NSSF
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: nssf-sbi.default.svc.cluster.local #10.100.200.7 # IP used to register to NRF
        bindingIPv4: nssf-sbi.default.svc.cluster.local #10.100.200.7  # IP used to bind the service
        port: 8000 # Port used to bind the service
      serviceNameList: # the SBI services provided by this SMF, refer to TS 29.531
        - nnssf-nsselection # Nnssf_NSSelection service
        - nnssf-nssaiavailability # Nnssf_NSSAIAvailability service
      nrfUri: http://nrf-sbi.default.svc.cluster.local:8000 # a valid URI of NRF
      supportedPlmnList: # the PLMNs (Public land mobile network) list supported by this NSSF
        - mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      supportedNssaiInPlmnList: # Supported S-NSSAI List for each PLMN
        - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          supportedSnssaiList: # Supported S-NSSAIs of the PLMN
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      nsiList: # List of available Network Slice Instance (NSI)
        - snssai: # S-NSSAI of this NSI
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          nsiInformationList: # Information list of this NSI
            # the NRF to be used to select the NFs/services within the selected NSI, and an optonal ID
            - nrfId: http://nrf-sbi.default.svc.cluster.local:8000/nnrf-nfm/v1/nf-instances
              nsiId: 10
        - snssai: # S-NSSAI of this NSI
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
            sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
          nsiInformationList: # Information list of this NSI
            # the NRF to be used to select the NFs/services within the selected NSI, and an optonal ID
            - nrfId: http://nrf-sbi.default.svc.cluster.local:8000/nnrf-nfm/v1/nf-instances
              nsiId: 22
        - snssai: # S-NSSAI of this NSI
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
            sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
          nsiInformationList: # Information list of this NSI
            # the NRF to be used to select the NFs/services within the selected NSI, and an optonal ID
            - nrfId: http://nrf-sbi.default.svc.cluster.local:8000/nnrf-nfm/v1/nf-instances
              nsiId: 23

    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      NSSF:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
