apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: subnet-wf
  name: 5g-subnet-010203
  namespace: 5g-core
spec:
  channel: gitops-chn-ns/gitops
  placement:
    clusters:
    - name: cluster1
  packageOverrides:
  - packageName: fiveg-subnet
    packageOverrides:
    - path: metadata.name
      value: 5g-subnet-010203
    - path: spec.arguments.parameters
      value:
      - name: network_name
        value: "OVERRIDE"
      - name: network_master
        value: "ens192"
      - name: network_range
        value: "10.20.0.0/24"
      - name: network_start
        value: "10.20.0.2"
      - name: network_end
        value: "10.20.0.50"

      - name: smf_name
        value: smf-sample

      - name: sst
        value: "1"
      - name: sd
        value: "010203"
