apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: app-wf
  name: my-5g-app-instance
  namespace: 5g-core
spec:
  channel: gitops-chn-ns/gitops
  placement:
    clusters:
    - name: paris-1
  packageOverrides:
  - packageName: fiveg-app
    packageOverrides:
    - path: metadata.name
      value: my-5g-app-instance
    - path: spec.arguments.parameters
      value:
      - name: network_name
        value: "gilan"
